# -*- coding: utf-8 -*-
"""automate_Muhamad Rivaldo Maulana

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17A6kiLNP1MY5-MviG8p0IjKeVqwLmp-z

# **1. Perkenalan Dataset**
"""

# automate_Rivaldo.py
# Automasi Data Preprocessing sesuai hasil eksperimen (EDA & Preprocessing)

import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder


def preprocess_data(
    input_path="Social_Network_Ads.csv",
    output_path="dataset_preprocessing.csv"
):
    """
    Fungsi untuk melakukan preprocessing data secara otomatis
    sesuai dengan hasil eksperimen pada notebook.
    """

    # 1. Load dataset
    df = pd.read_csv(input_path)
    print("Dataset berhasil dimuat")

    # 2. Menghapus data duplikat (jika ada)
    df = df.drop_duplicates()

    # 3. Handling missing value
    df.fillna(df.mean(numeric_only=True), inplace=True)

    # 4. Encoding target (Purchased)
    if df['Purchased'].dtype == 'object':
        le = LabelEncoder()
        df['Purchased'] = le.fit_transform(df['Purchased'])

    # 5. Pemisahan fitur dan target
    X = df.drop(columns=['Purchased'])
    y = df['Purchased']

    # 6. Standardisasi fitur numerik
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # 7. Menggabungkan kembali fitur dan target
    df_preprocessed = pd.DataFrame(X_scaled, columns=X.columns)
    df_preprocessed['Purchased'] = y.values

    # 8. Simpan dataset hasil preprocessing
    df_preprocessed.to_csv(output_path, index=False)
    print("Dataset preprocessing berhasil disimpan")

    return df_preprocessed


if __name__ == "__main__":
    preprocess_data()